### PR TITLE
fix license in recipe

### PR DESCRIPTION
**Pull request by esc**
Fix location of license and project URL too.

The location of the license will be correct with the next release.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by esc** [comment]
I changed the PR to fix only the licenses.

**Comment by esc** [comment]
@conda-forge-admin, please rerender

**Comment by esc** [comment]
@FrancescElies @danielfrg @beckermr any chance one of you could look at this? Should I really bump the build number?

**Review by beckermr — CHANGES_REQUESTED** [review]
Yes I’d bump the build number. This will force the correct license to be distributed.

**Comment by esc** [comment]
@beckermr done

**Comment by esc** [comment]
@beckermr do I need to re-render now?

**Comment by esc** [comment]
I'll do it anyway.

**Comment by esc** [comment]
@conda-forge-admin, please rerender

**Review by beckermr — APPROVED** [review]

**Comment by beckermr** [comment]
@esc Sorry for the delay on this.

**Comment by esc** [comment]
@beckermr thanks for the merge!

Do you have any idea why the package listing on anaconda.org is still showing the Apache 2.0 license?

https://anaconda.org/conda-forge/python-blosc

It say, ` Last upload: 19 hours and a few seconds ago ` so that was probably the build triggered by merging the PR, right? This means, the issue isn't being caused by a delayed build or anything else, but we must look for it elsewhere.

**Comment by esc** [comment]
Maybe it only get's picked up when there is a new release? Because it would perhaps cause legal troubles to change license between builds but not between releases? In any case, a new release for python-blosc shouldn't be too far away.

**Comment by beckermr** [comment]
I don't know. They may not refresh their web pages? You'd have to ask them...

**Pull request merged**
