### PR TITLE
ENH conda build 3

### PR DESCRIPTION
**Pull request by beckermr**
Closes #14 
Closes #13 
Closes #7 
Closes #11 

@conda-forge-admin, please update for conda-build 3

### CODE REVIEW

**Comment by beckermr** [comment]
It looks like this line from the doctests fails:

```python
b"" == blosc.decompress(blosc.compress(b"", 1))
```

The source code at this line has not been touched in 6 years, so my guess is that something in the C layer changed underneath.

**Comment by beckermr** [comment]
We just merged v1.15.1 of `c-blosc`. We can retry this update with that version of the C.

**Comment by jakirkham** [comment]
Have restarted CIs in case that helps. 😄

**Comment by beckermr** [comment]
I was waiting for blosc ci to complete and then the 20 minute delay to get the repo metadata to the static server.

**Comment by beckermr** [comment]
Wooooooooo! This PR is good to go @conda-forge/python-blosc @jakirkham !

**Comment by jakirkham** [comment]
Thanks @beckermr 😄

**Pull request merged**
